const timelineElements = [
  {
    id: 1,
    title: "Web Development Intern",
    location: "Emarkable, Offaly, Ireland",
    description: "Transition Year Work Experience",
    buttonText: "Details",
    date: "2008-2008",
    icon: "work",
    color: "blue",
    tech: ["HTML", "Wordpress"],
  },
  {
    id: 2,
    title: "Graduated from College",
    location: "BCFE, Dublin, Ireland",
    description: "Completed a BTEC HND in Computer Games Design",
    buttonText: "Details",
    date: "2010-2013",
    icon: "school",
    color: "blue",
    tech: ["JavaScript", "HTML", "Java", "Unity", "C#", "3D Modelling"],
  },
  {
    id: 3,
    title: "Junior Game Developer",
    location: "Riot Games and Havok, Dublin, Ireland",
    description:
      "Got industry experience, guidance by industry leaders, Hands-on experience with new engines",
    buttonText: "Details",
    date: "2013-2014",
    icon: "work",
    color: "purple",
    tech: ["C#", "Lua", "Perforce", "Agile", "App Development"],
  },
  {
    id: 4,
    title: "Game Development Lead",
    location: "Polystorm, Dublin, Ireland",
    description:
      "Designed and developed games, Integrated APIs, Website Development",
    buttonText: "Details",
    date: "2014-2015",
    icon: "work",
    color: "yellow",
    tech: [
      "C#",
      "Unity",
      "Agile",
      "Photoshop",
      "HTML",
      "CSS",
      "Wordpress",
      "Play Store",
      "App Store",
    ],
  },
  {
    id: 5,
    title: "Upskilled in Web Design",
    location: "TUD, Dublin, Ireland",
    description: "Completed a course in Digital Media & Web Design",
    buttonText: "Details",
    date: "2015-2016",
    icon: "school",
    color: "orange",
    tech: ["JavaScript", "HTML", "CSS", "Photoshop", "Wordpress"],
  },
  {
    id: 6,
    title: "Self Employed App Developer",
    location: "Leoplureodon, Dublin, Ireland",
    description: "Released 2 sucessful apps, over 30,000 installs",
    buttonText: "Details",
    date: "2016-2017",
    icon: "work",
    color: "red",
    tech: [
      "C#",
      "Agile",
      "Unity",
      "Photoshop",
      "HTML",
      "CSS",
      "Wordpress",
      "Play Store",
      "App Store",
    ],
  },
  {
    id: 7,
    title: "VR/AR Developer & Immersive Technology Specialist",
    location: "General Motors, Dublin, Ireland",
    description:
      "Led projects, Created Visualizations, Online/Offline Vehicle Configurators, Interactive Experiences, Optimised Workflows",
    buttonText: "Details",
    date: "2017-2022",
    icon: "work",
    color: "orange",
    tech: [
      "Unity",
      "Unreal Engine",
      "ThreeJS",
      "Visual Studio",
      "Agile",
      "C#",
      "C++",
      "Batch",
      "Typescript",
      "Blueprints",
      "Python",
      "Photoshop",
      "3D Modelling",
      "Bitbucket",
      "Perforce",
      "AWS",
      "Google Cloud",
    ],
  },
  {
    id: 8,
    title: "Full Stack Developer",
    location: "General Motors, Dublin, Ireland",
    description:
      "Transitioned to Full Stack, Created company-wide websites, Application Monitoring",
    buttonText: "Details",
    date: "2022-2024",
    icon: "work",
    color: "orange",
    tech: [
      "React",
      "HTML",
      "CSS",
      "REST API",
      "Databases",
      "Front End",
      "Back End",
      "Dev Ops",
      "CI/CD",
      "Agile",
      "Vite",
      "Node JS",
      "TypeScript",
      "C#",
      "Javascript",
      "Java",
      "Azure Dev Ops",
      "PostgreSQL",
      "MySQL",
      "Git",
      "Github",
      "Docker",
    ],
  },
];

export default timelineElements.reverse();
